package dev.orwell.bucket.detection;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.Objects;

/**
 * Hands out {@code frame_events} ids before the row exists.
 *
 * <p>This is what lets the hub broadcast a frame without waiting for Postgres: the SSE event id is
 * the row id, so the id has to exist first, and the write can then happen behind the live stream
 * instead of in front of it.
 *
 * <p>Ids come from a real sequence rather than an in-process counter, so two detection instances
 * sharing the database cannot mint the same id. The sequence increments in blocks and each
 * {@code nextval} reserves the whole block for this process, which keeps the round trips down to
 * one per {@value #BLOCK} frames.
 */
@Component
public class FrameIdAllocator {
    /** Ids reserved per round trip. Also the sequence's INCREMENT. */
    private static final int BLOCK = 64;
    static final String SEQUENCE = "frame_events_seq";

    private final JdbcTemplate jdbc;
    private long next;
    private long limit;
    private boolean initialised;

    public FrameIdAllocator(JdbcTemplate jdbc) {
        this.jdbc = Objects.requireNonNull(jdbc, "jdbc");
    }

    /**
     * Creates the sequence if it is missing and moves it past any rows already in the table.
     * {@code ddl-auto} does not manage it, because the id is assigned by this class rather than
     * generated by Hibernate.
     *
     * <p>Called on first allocation rather than from {@code @PostConstruct}: this bean depends on
     * the {@code JdbcTemplate}, not on the entity manager factory, so at construction time
     * Hibernate may not have created {@code frame_events} yet and the MAX(id) read below would
     * fail. By the time a frame is being ingested, the schema is certainly there.
     */
    void ensureSequence() {
        jdbc.execute("CREATE SEQUENCE IF NOT EXISTS " + SEQUENCE + " INCREMENT " + BLOCK);
        // Rows written before this class existed used an identity column starting at 1, so the
        // sequence has to start above the highest id already present or the two would collide.
        Long highest = jdbc.queryForObject(
                "SELECT GREATEST(COALESCE((SELECT MAX(id) FROM frame_events), 0), "
                        + "COALESCE(last_value, 0)) FROM " + SEQUENCE, Long.class);
        if (highest != null && highest > 0) {
            jdbc.queryForObject("SELECT setval('" + SEQUENCE + "', ?)", Long.class, highest);
        }
    }

    /** The next free id. Synchronized: one shared block, many ingest threads. */
    public synchronized long next() {
        if (!initialised) {
            ensureSequence();
            initialised = true;
        }
        if (next > limit) {
            long reserved = Objects.requireNonNull(
                    jdbc.queryForObject("SELECT nextval('" + SEQUENCE + "')", Long.class));
            // nextval advanced the sequence by BLOCK, so [reserved, reserved + BLOCK - 1] is ours
            // and no other process can be handed any of it.
            next = reserved;
            limit = reserved + BLOCK - 1;
        }
        return next++;
    }
}
